import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import { FaGithub, FaLinkedin, FaTwitter } from "react-icons/fa";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <div className={styles.leftSidebarCol}>
          <Link href="https://github.com/batyr-qhan" passHref>
            <a target="_blank">
              <FaGithub
                size="1.5rem"
                className={styles.icon}
                onClick={() => {}}
              />
            </a>
          </Link>

          <Link href="https://www.linkedin.com/in/batyrqh/" passHref>
            <a target="_blank">
              <FaLinkedin size="1.5rem" className={styles.icon} />
            </a>
          </Link>

          {/* <FaTwitter size="1.5rem" className={styles.icon} /> */}
        </div>
        <div className={`image-col ${styles.imageContainerCol}`}>
          <div className={styles.mainTitleContainer}>
            <h1 className={styles.mainTitle}>hi there</h1>
          </div>
        </div>
        <div></div>
        <div className="content-col">
          <div className="content-col__title-container">
            <span className="content-col__title droid-sans-bold">ABOUT ME</span>
          </div>
          <p className="content-col__subtitle inconsolata-bold">
            Im a frontend and React Native developer who enjoys creating cool things
          </p>
          <p className="content-col__text inconsolata-normal">
            Proficient in JavaScript, TypeScript, React, CSS, Expo, and more other web and mobile
            related tools.
          </p>
          <div className="content-col__title-container">
            <span className="content-col__title droid-sans-bold">
              SKILLS & SERVICES:{" "}
            </span>
          </div>
          <div className={styles.skillsContainer}>
            <span className={styles.skillsItem}>#JAVASCRIPT</span>
            <span className={styles.skillsItem}>#TYPESCRIPT</span>
            <span className={styles.skillsItem}>#REACT</span>
            <span className={styles.skillsItem}>#CSS</span>
            <span className={styles.skillsItem}>#NODE.JS</span>
            <span className={styles.skillsItem}>#NEXT.JS</span>
          </div>
          <div className={styles.viewExperience}>
            <span className={styles.viewExperience__text}>
              <Link
                href="/experience
              "
              >
                View details
              </Link>
            </span>

            <div className={styles.iconArrowContainer}>
              <div className={styles.arrowLeft}></div>
              <div className={styles.iconArrow}></div>
            </div>
          </div>
        </div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </>
  );
}
